# Generated by Django 4.0.2 on 2022-06-22 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=200)),
                ('editora', models.CharField(max_length=100)),
                ('anoPublicacao', models.IntegerField()),
                ('isbn', models.CharField(max_length=20)),
                ('quantidade', models.IntegerField()),
                ('serieAlvo', models.IntegerField()),
                ('imagem', models.ImageField(blank=True, upload_to='catalogo/media')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogos.disciplina', verbose_name='Disciplina')),
            ],
        ),
    ]
