# Generated by Django 4.0.2 on 2022-06-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0003_alter_disciplina_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='disciplina',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Disciplina',
        ),
    ]
