# Generated by Django 4.0.2 on 2022-06-23 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0006_alter_livro_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='disciplina',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='catalogos.disciplina', verbose_name='Disciplina'),
        ),
    ]
