# Generated by Django 4.0.2 on 2022-06-30 21:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalogos', '0008_alter_livro_imagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livro',
            options={'verbose_name': 'Livros Didáticos'},
        ),
        migrations.AlterField(
            model_name='livro',
            name='serieAlvo',
            field=models.CharField(blank=True, choices=[('1', ' 1° ano'), ('2', '2° ano'), ('3', '3° ano')], max_length=1),
        ),
        migrations.CreateModel(
            name='Avaliacao',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text=' ID particular', primary_key=True, serialize=False)),
                ('due_back', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(blank=True, choices=[('d', 'Disponivel'), ('a', 'Agendado'), ('s', 'Solicitado'), ('e', 'Emprestado')], default='d', help_text='Situação do Livro', max_length=1)),
                ('docente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='accounts.docente')),
                ('livro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='catalogos.livro')),
            ],
            options={
                'verbose_name': 'Avaliação',
            },
        ),
    ]
